<a href="https://colab.research.google.com/github/Abrar-404/AI-ML_Practices_and_Assignments/blob/main/Module_10_Practice_Problems.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

# Problem 01

In [2]:
series = pd.Series([10, 20, 30, 40, 50])

series

series.index

series.dtype

dtype('int64')

In [3]:
data = {
    "Name" : ["Goku", "Vegeta", "Frieza", "Gohan", "Piccolo"],
    "Age" : [40, 50, 60, 30, 70],
    "City": ["New York", "London", "Paris", "Tokyo", "Sydney"]
       }

df = pd.DataFrame(data, index=[1, 2, 3, 4, 5])

df

      Name  Age      City
1     Goku   40  New York
2   Vegeta   50    London
3   Frieza   60     Paris
4    Gohan   30     Tokyo
5  Piccolo   70    Sydney

# Problem 02

In [4]:
df = pd.read_csv('sample_data/student_data.csv')

df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka

In [16]:
row, col = df.shape

print(f"rows: {row}, columns: {col}")

df.dtypes

df.describe()

rows: 20, columns: 9

       Data Structure Marks  Algorithm Marks  Python Marks
count             16.000000        16.000000     15.000000
mean              84.000000        84.000000     85.666667
std                6.501282         6.501282      5.394000
min               72.000000        72.000000     76.000000
25%               79.500000        79.500000     83.000000
50%               85.500000        85.500000     85.000000
75%               88.250000        88.250000     88.500000
max               94.000000        94.000000     95.000000

# Problem 03

In [21]:
data = {
    'Product': ['Pen', 'Book', 'Eraser', 'Pencil'],
    'Price': [10, 50, 5, 7],
    'Quantity': [100, 60, 200, 150]
}

new_data = pd.DataFrame(data)
new_data

  Product  Price  Quantity
0     Pen     10       100
1    Book     50        60
2  Eraser      5       200
3  Pencil      7       150

In [22]:
new_data.columns

Index(['Product', 'Price', 'Quantity'], dtype='object')

In [23]:
new_data.index

RangeIndex(start=0, stop=4, step=1)

In [24]:
new_data["Quantity"]

0    100
1     60
2    200
3    150
Name: Quantity, dtype: int64

In [25]:
len(new_data["Quantity"])

4

In [34]:
new_data.loc[1]

Product     Book
Price         50
Quantity      60
Name: 1, dtype: object

# Problem 04

In [37]:
# first row
df.loc[0]
df.iloc[0]

StudentID                    PH1001
FullName                Alif Rahman
Data Structure Marks           85.0
Algorithm Marks                85.0
Python Marks                   88.0
CompletionStatus          Completed
EnrollmentDate           2024-01-15
Instructor                Mr. Karim
Location                      Dhaka
Name: 0, dtype: object

In [45]:
# second column
second_col = df.loc[:, "FullName"]
print(second_col)

second_col = df.iloc[:, 1]
print(second_col)

0          Alif Rahman
1        Fatima Akhter
2        Imran Hossain
3     Jannatul Ferdous
4          Kamal Uddin
5          Laila Begum
6       Mahmudul Hasan
7          Nadia Islam
8           Omar Faruq
9         Priya Sharma
10        Rahim Sheikh
11     Sadia Chowdhury
12        Tanvir Ahmed
13          Urmi Akter
14        Wahiduzzaman
15        Ziaur Rahman
16         Afsana Mimi
17         Babul Ahmed
18        Faria Rahman
19          Nasir Khan
Name: FullName, dtype: object
0          Alif Rahman
1        Fatima Akhter
2        Imran Hossain
3     Jannatul Ferdous
4          Kamal Uddin
5          Laila Begum
6       Mahmudul Hasan
7          Nadia Islam
8           Omar Faruq
9         Priya Sharma
10        Rahim Sheikh
11     Sadia Chowdhury
12        Tanvir Ahmed
13          Urmi Akter
14        Wahiduzzaman
15        Ziaur Rahman
16         Afsana Mimi
17         Babul Ahmed
18        Faria Rahman
19          Nasir Khan
Name: FullName, dtype: object

In [48]:
# 2 x 2 block from the middle

df

show_block = df.iloc[9:11, 4:6]
print(show_block)

    Python Marks CompletionStatus
9           88.0        Completed
10          91.0      In Progress

# Problem 05

In [55]:
# creating a dataframe
data = {
    "StudentName" : ["Hulk", "Thor", "Tony", "Cap", "Hawkeye"],
    "Marks" : [90, 50, 99, 80, 23],
    "Status": ["A+", "B-", "A+", "A", "F"]
}

students = pd.DataFrame(data, index=[1,2,3,4,5])
students

  StudentName  Marks Status
1        Hulk     90     A+
2        Thor     50     B-
3        Tony     99     A+
4         Cap     80      A
5     Hawkeye     23      F

In [61]:
# drop a column
drop_col = students.drop('Status', axis=1)

drop_col

  StudentName  Marks
1        Hulk     90
2        Thor     50
3        Tony     99
4         Cap     80
5     Hawkeye     23

In [62]:
# drop a row by index
drop_row = students.drop(2)
drop_row

  StudentName  Marks Status
1        Hulk     90     A+
3        Tony     99     A+
4         Cap     80      A
5     Hawkeye     23      F

# Problem 06

In [69]:
#creating a dataframe
datas = {
    "Name":["Ema", "John", 'Albert', 'James', "Nadia"],
    "Department":['Sales', 'Management', 'IT', 'HR', 'Clerk'],
    "Salary":[10000, 30000, 350000, 60000, 20000]
}

employees = pd.DataFrame(datas, index=[1,2,3,4,5])
employees

     Name  Department  Salary
1     Ema       Sales   10000
2    John  Management   30000
3  Albert          IT  350000
4   James          HR   60000
5   Nadia       Clerk   20000

In [75]:
# Ascending order by Salary
salary = employees.sort_values('Salary', ascending=True)
salary

     Name  Department  Salary
1     Ema       Sales   10000
5   Nadia       Clerk   20000
2    John  Management   30000
4   James          HR   60000
3  Albert          IT  350000

In [76]:
# Descending order by Name
Names = employees.sort_values('Name', ascending=False)
Names

     Name  Department  Salary
5   Nadia       Clerk   20000
2    John  Management   30000
4   James          HR   60000
1     Ema       Sales   10000
3  Albert          IT  350000

In [77]:
# Sort by Salary and Names
copy = employees.sort_values(['Department', 'Salary'], ascending=[True, False])
copy

     Name  Department  Salary
5   Nadia       Clerk   20000
4   James          HR   60000
3  Albert          IT  350000
2    John  Management   30000
1     Ema       Sales   10000

# Problem 07

In [91]:
#creating a dataframe
data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eva", "Frank", "Grace", "Henry"],
    "Score": [85, 72, 90, 66, 39, 94, 33, 81]
}

chatro = pd.DataFrame(data, index=[1,2,3,4,5,6,7,8])
chatro

      Name  Score
1    Alice     85
2      Bob     72
3  Charlie     90
4    David     66
5      Eva     39
6    Frank     94
7    Grace     33
8    Henry     81

In [92]:
# Score > 60
greater_than = chatro.loc[(chatro['Score'] > 60)]
greater_than

      Name  Score
1    Alice     85
2      Bob     72
3  Charlie     90
4    David     66
6    Frank     94
8    Henry     81

In [93]:
# Score < 40.
less_than = chatro.loc[(chatro['Score'] < 40)]
less_than

    Name  Score
5    Eva     39
7  Grace     33