<a href="https://colab.research.google.com/github/Abrar-404/AI-ML_Practices_and_Assignments/blob/main/Module_07.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer

In [ ]:
df = pd.read_csv('titanic_data_updated.csv')

In [ ]:
X = df.drop(['Survived'],axis=1)

X

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,third,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,first,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,third,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,first,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,third,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
886,887,second,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,first,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,third,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,first,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,third,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
y = df['Survived']

y

0       no
1      yes
2      yes
3      yes
4       no
      ...
886     no
887    yes
888     no
889    yes
890     no
Name: Survived, Length: 891, dtype: object

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [ ]:
X_train
display(y_train)

331     no
733     no
382     no
704     no
813     no
      ...
106    yes
270     no
860     no
435    yes
102     no
Name: Survived, Length: 712, dtype: object

In [ ]:
X_test
display(y_test)

709    yes
439     no
840     no
720    yes
39     yes
      ...
433     no
773     no
25     yes
84     yes
10     yes
Name: Survived, Length: 179, dtype: object

# Ordinal Encoding

In [ ]:
from sklearn.preprocessing import OrdinalEncoder

In [ ]:
pclass_encoder = OrdinalEncoder(categories = [['third', 'second', 'first']])

pclass_encoder.fit(X_train[['Pclass']])

X_train['encoded_pclass'] = pclass_encoder.transform(X_train[['Pclass']]).ravel()
X_test['encoded_pclass'] = pclass_encoder.transform(X_test[['Pclass']]).ravel()

X_test

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,encoded_pclass
709,710,third,"Moubarek, Master. Halim Gonios (""William George"")",male,NaN,1,1,2661,15.2458,NaN,C,0.0
439,440,second,"Kvillner, Mr. Johan Henrik Johannesson",male,31.0,0,0,C.A. 18723,10.5000,NaN,S,1.0
840,841,third,"Alhomaki, Mr. Ilmari Rudolf",male,20.0,0,0,SOTON/O2 3101287,7.9250,NaN,S,0.0
720,721,second,"Harper, Miss. Annie Jessie ""Nina""",female,6.0,0,1,248727,33.0000,NaN,S,1.0
39,40,third,"Nicola-Yarred, Miss. Jamila",female,14.0,1,0,2651,11.2417,NaN,C,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
433,434,third,"Kallio, Mr. Nikolai Erland",male,17.0,0,0,STON/O 2. 3101274,7.1250,NaN,S,0.0
773,774,third,"Elias, Mr. Dibo",male,NaN,0,0,2674,7.2250,NaN,C,0.0
25,26,third,"Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...",female,38.0,1,5,347077,31.3875,NaN,S,0.0
84,85,second,"Ilett, Miss. Bertha",female,17.0,0,0,SO/C 14885,10.5000,NaN,S,1.0
10,11,third,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S,0.0

# One hot Encoding

In [ ]:
from sklearn.preprocessing import OneHotEncoder

In [ ]:
sex_ohe = OneHotEncoder(sparse_output=False).set_output(transform = 'pandas')

sex_ohe.fit(X_train[['Sex']])

encoded_sex = sex_ohe.transform(X_train[['Sex']])

X_train = pd.concat([X_train, encoded_sex], axis = 1)

X_train

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,encoded_pclass,Sex_female,Sex_male
331,332,first,"Partner, Mr. Austen",male,45.5,0,0,113043,28.5000,C124,S,2.0,0.0,1.0
733,734,second,"Berriman, Mr. William John",male,23.0,0,0,28425,13.0000,NaN,S,1.0,0.0,1.0
382,383,third,"Tikkanen, Mr. Juho",male,32.0,0,0,STON/O 2. 3101293,7.9250,NaN,S,0.0,0.0,1.0
704,705,third,"Hansen, Mr. Henrik Juul",male,26.0,1,0,350025,7.8542,NaN,S,0.0,0.0,1.0
813,814,third,"Andersson, Miss. Ebba Iris Alfrida",female,6.0,4,2,347082,31.2750,NaN,S,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106,107,third,"Salkjelsvik, Miss. Anna Kristine",female,21.0,0,0,343120,7.6500,NaN,S,0.0,1.0,0.0
270,271,first,"Cairns, Mr. Alexander",male,NaN,0,0,113798,31.0000,NaN,S,2.0,0.0,1.0
860,861,third,"Hansen, Mr. Claus Peter",male,41.0,2,0,350026,14.1083,NaN,S,0.0,0.0,1.0
435,436,first,"Carter, Miss. Lucile Polk",female,14.0,1,2,113760,120.0000,B96 B98,S,2.0,1.0,0.0
102,103,first,"White, Mr. Richard Frasar",male,21.0,0,1,35281,77.2875,D26,S,2.0,0.0,1.0

In [ ]:
embarked_ohe = OneHotEncoder(sparse_output=False).set_output(transform = 'pandas')

embarked_ohe.fit(X_train[['Embarked']])

encoded_embarked = embarked_ohe.transform(X_train[['Embarked']])

X_train = pd.concat([X_train, encoded_embarked], axis = 1)

X_train

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,encoded_pclass,Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S,Embarked_nan
331,332,first,"Partner, Mr. Austen",male,45.5,0,0,113043,28.5000,C124,S,2.0,0.0,1.0,0.0,0.0,1.0,0.0
733,734,second,"Berriman, Mr. William John",male,23.0,0,0,28425,13.0000,NaN,S,1.0,0.0,1.0,0.0,0.0,1.0,0.0
382,383,third,"Tikkanen, Mr. Juho",male,32.0,0,0,STON/O 2. 3101293,7.9250,NaN,S,0.0,0.0,1.0,0.0,0.0,1.0,0.0
704,705,third,"Hansen, Mr. Henrik Juul",male,26.0,1,0,350025,7.8542,NaN,S,0.0,0.0,1.0,0.0,0.0,1.0,0.0
813,814,third,"Andersson, Miss. Ebba Iris Alfrida",female,6.0,4,2,347082,31.2750,NaN,S,0.0,1.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106,107,third,"Salkjelsvik, Miss. Anna Kristine",female,21.0,0,0,343120,7.6500,NaN,S,0.0,1.0,0.0,0.0,0.0,1.0,0.0
270,271,first,"Cairns, Mr. Alexander",male,NaN,0,0,113798,31.0000,NaN,S,2.0,0.0,1.0,0.0,0.0,1.0,0.0
860,861,third,"Hansen, Mr. Claus Peter",male,41.0,2,0,350026,14.1083,NaN,S,0.0,0.0,1.0,0.0,0.0,1.0,0.0
435,436,first,"Carter, Miss. Lucile Polk",female,14.0,1,2,113760,120.0000,B96 B98,S,2.0,1.0,0.0,0.0,0.0,1.0,0.0
102,103,first,"White, Mr. Richard Frasar",male,21.0,0,1,35281,77.2875,D26,S,2.0,0.0,1.0,0.0,0.0,1.0,0.0

In [ ]:
X_train.sample(5)

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,encoded_pclass,Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S,Embarked_nan
752,753,third,"Vande Velde, Mr. Johannes Joseph",male,33.0,0,0,345780,9.5000,NaN,S,0.0,0.0,1.0,0.0,0.0,1.0,0.0
424,425,third,"Rosblom, Mr. Viktor Richard",male,18.0,1,1,370129,20.2125,NaN,S,0.0,0.0,1.0,0.0,0.0,1.0,0.0
182,183,third,"Asplund, Master. Clarence Gustaf Hugo",male,9.0,4,2,347077,31.3875,NaN,S,0.0,0.0,1.0,0.0,0.0,1.0,0.0
56,57,second,"Rugg, Miss. Emily",female,21.0,0,0,C.A. 31026,10.5000,NaN,S,1.0,1.0,0.0,0.0,0.0,1.0,0.0
7,8,third,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S,0.0,0.0,1.0,0.0,0.0,1.0,0.0

In [ ]:
X_train.drop(['Pclass', 'Sex', 'Embarked'], axis = 1, inplace = True)

In [ ]:
X_train

,PassengerId,Name,Age,SibSp,Parch,Ticket,Fare,Cabin,encoded_pclass,Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S,Embarked_nan
331,332,"Partner, Mr. Austen",45.5,0,0,113043,28.5000,C124,2.0,0.0,1.0,0.0,0.0,1.0,0.0
733,734,"Berriman, Mr. William John",23.0,0,0,28425,13.0000,NaN,1.0,0.0,1.0,0.0,0.0,1.0,0.0
382,383,"Tikkanen, Mr. Juho",32.0,0,0,STON/O 2. 3101293,7.9250,NaN,0.0,0.0,1.0,0.0,0.0,1.0,0.0
704,705,"Hansen, Mr. Henrik Juul",26.0,1,0,350025,7.8542,NaN,0.0,0.0,1.0,0.0,0.0,1.0,0.0
813,814,"Andersson, Miss. Ebba Iris Alfrida",6.0,4,2,347082,31.2750,NaN,0.0,1.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106,107,"Salkjelsvik, Miss. Anna Kristine",21.0,0,0,343120,7.6500,NaN,0.0,1.0,0.0,0.0,0.0,1.0,0.0
270,271,"Cairns, Mr. Alexander",NaN,0,0,113798,31.0000,NaN,2.0,0.0,1.0,0.0,0.0,1.0,0.0
860,861,"Hansen, Mr. Claus Peter",41.0,2,0,350026,14.1083,NaN,0.0,0.0,1.0,0.0,0.0,1.0,0.0
435,436,"Carter, Miss. Lucile Polk",14.0,1,2,113760,120.0000,B96 B98,2.0,1.0,0.0,0.0,0.0,1.0,0.0
102,103,"White, Mr. Richard Frasar",21.0,0,1,35281,77.2875,D26,2.0,0.0,1.0,0.0,0.0,1.0,0.0

In [ ]:
# transforming test data
encoded_df = embarked_ohe.transform(X_test[['Embarked']])
X_test = pd.concat([X_test,encoded_df],axis =1)

In [ ]:
X_test.drop(['Pclass', 'Sex', 'Embarked'], axis = 1, inplace = True)

In [ ]:
X_test

,PassengerId,Name,Age,SibSp,Parch,Ticket,Fare,Cabin,encoded_pclass,Embarked_C,Embarked_Q,Embarked_S,Embarked_nan
709,710,"Moubarek, Master. Halim Gonios (""William George"")",NaN,1,1,2661,15.2458,NaN,0.0,1.0,0.0,0.0,0.0
439,440,"Kvillner, Mr. Johan Henrik Johannesson",31.0,0,0,C.A. 18723,10.5000,NaN,1.0,0.0,0.0,1.0,0.0
840,841,"Alhomaki, Mr. Ilmari Rudolf",20.0,0,0,SOTON/O2 3101287,7.9250,NaN,0.0,0.0,0.0,1.0,0.0
720,721,"Harper, Miss. Annie Jessie ""Nina""",6.0,0,1,248727,33.0000,NaN,1.0,0.0,0.0,1.0,0.0
39,40,"Nicola-Yarred, Miss. Jamila",14.0,1,0,2651,11.2417,NaN,0.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
433,434,"Kallio, Mr. Nikolai Erland",17.0,0,0,STON/O 2. 3101274,7.1250,NaN,0.0,0.0,0.0,1.0,0.0
773,774,"Elias, Mr. Dibo",NaN,0,0,2674,7.2250,NaN,0.0,1.0,0.0,0.0,0.0
25,26,"Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...",38.0,1,5,347077,31.3875,NaN,0.0,0.0,0.0,1.0,0.0
84,85,"Ilett, Miss. Bertha",17.0,0,0,SO/C 14885,10.5000,NaN,1.0,0.0,0.0,1.0,0.0
10,11,"Sandstrom, Miss. Marguerite Rut",4.0,1,1,PP 9549,16.7000,G6,0.0,0.0,0.0,1.0,0.0

# Encoding the Cabin features

In [ ]:
X_train['Cabin'].value_counts()

Cabin
C23 C25 C27    4
C22 C26        3
F2             3
G6             3
B96 B98        3
              ..
A14            1
D49            1
C87            1
D56            1
C62 C64        1
Name: count, Length: 117, dtype: int64

In [ ]:
X_train['Cabin'].dtype

dtype('O')

In [ ]:
X_train['Cabin_Deck'] = X_train['Cabin'].astype(str).str[0]

X_train

,PassengerId,Name,Age,SibSp,Parch,Ticket,Fare,Cabin,encoded_pclass,Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S,Embarked_nan,Cabin_Deck
331,332,"Partner, Mr. Austen",45.5,0,0,113043,28.5000,C124,2.0,0.0,1.0,0.0,0.0,1.0,0.0,C
733,734,"Berriman, Mr. William John",23.0,0,0,28425,13.0000,NaN,1.0,0.0,1.0,0.0,0.0,1.0,0.0,n
382,383,"Tikkanen, Mr. Juho",32.0,0,0,STON/O 2. 3101293,7.9250,NaN,0.0,0.0,1.0,0.0,0.0,1.0,0.0,n
704,705,"Hansen, Mr. Henrik Juul",26.0,1,0,350025,7.8542,NaN,0.0,0.0,1.0,0.0,0.0,1.0,0.0,n
813,814,"Andersson, Miss. Ebba Iris Alfrida",6.0,4,2,347082,31.2750,NaN,0.0,1.0,0.0,0.0,0.0,1.0,0.0,n
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106,107,"Salkjelsvik, Miss. Anna Kristine",21.0,0,0,343120,7.6500,NaN,0.0,1.0,0.0,0.0,0.0,1.0,0.0,n
270,271,"Cairns, Mr. Alexander",NaN,0,0,113798,31.0000,NaN,2.0,0.0,1.0,0.0,0.0,1.0,0.0,n
860,861,"Hansen, Mr. Claus Peter",41.0,2,0,350026,14.1083,NaN,0.0,0.0,1.0,0.0,0.0,1.0,0.0,n
435,436,"Carter, Miss. Lucile Polk",14.0,1,2,113760,120.0000,B96 B98,2.0,1.0,0.0,0.0,0.0,1.0,0.0,B
102,103,"White, Mr. Richard Frasar",21.0,0,1,35281,77.2875,D26,2.0,0.0,1.0,0.0,0.0,1.0,0.0,D

In [ ]:
X_train['Cabin_Deck'].value_counts()

Cabin_Deck
n    553
C     52
B     38
E     24
D     19
F     12
A     10
G      3
T      1
Name: count, dtype: int64

In [ ]:
X_test['Cabin_Deck'] = X_test['Cabin'].astype(str).str[0]
X_test

,PassengerId,Name,Age,SibSp,Parch,Ticket,Fare,Cabin,encoded_pclass,Embarked_C,Embarked_Q,Embarked_S,Embarked_nan,Cabin_Deck
709,710,"Moubarek, Master. Halim Gonios (""William George"")",NaN,1,1,2661,15.2458,NaN,0.0,1.0,0.0,0.0,0.0,n
439,440,"Kvillner, Mr. Johan Henrik Johannesson",31.0,0,0,C.A. 18723,10.5000,NaN,1.0,0.0,0.0,1.0,0.0,n
840,841,"Alhomaki, Mr. Ilmari Rudolf",20.0,0,0,SOTON/O2 3101287,7.9250,NaN,0.0,0.0,0.0,1.0,0.0,n
720,721,"Harper, Miss. Annie Jessie ""Nina""",6.0,0,1,248727,33.0000,NaN,1.0,0.0,0.0,1.0,0.0,n
39,40,"Nicola-Yarred, Miss. Jamila",14.0,1,0,2651,11.2417,NaN,0.0,1.0,0.0,0.0,0.0,n
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
433,434,"Kallio, Mr. Nikolai Erland",17.0,0,0,STON/O 2. 3101274,7.1250,NaN,0.0,0.0,0.0,1.0,0.0,n
773,774,"Elias, Mr. Dibo",NaN,0,0,2674,7.2250,NaN,0.0,1.0,0.0,0.0,0.0,n
25,26,"Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...",38.0,1,5,347077,31.3875,NaN,0.0,0.0,0.0,1.0,0.0,n
84,85,"Ilett, Miss. Bertha",17.0,0,0,SO/C 14885,10.5000,NaN,1.0,0.0,0.0,1.0,0.0,n
10,11,"Sandstrom, Miss. Marguerite Rut",4.0,1,1,PP 9549,16.7000,G6,0.0,0.0,0.0,1.0,0.0,G

In [ ]:
deck_ohe = OneHotEncoder(sparse_output=False, drop = 'first').set_output(transform = 'pandas')

deck_ohe.fit(X_train[['Cabin_Deck']])

deck_encoded = deck_ohe.transform(X_train[['Cabin_Deck']])

X_train = pd.concat([X_train, deck_encoded], axis = 1)

X_train

,PassengerId,Name,Age,SibSp,Parch,Ticket,Fare,Cabin,encoded_pclass,Sex_female,...,Cabin_Deck_T,Cabin_Deck_n,Cabin_Deck_B,Cabin_Deck_C,Cabin_Deck_D,Cabin_Deck_E,Cabin_Deck_F,Cabin_Deck_G,Cabin_Deck_T,Cabin_Deck_n
331,332,"Partner, Mr. Austen",45.5,0,0,113043,28.5000,C124,2.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
733,734,"Berriman, Mr. William John",23.0,0,0,28425,13.0000,NaN,1.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
382,383,"Tikkanen, Mr. Juho",32.0,0,0,STON/O 2. 3101293,7.9250,NaN,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
704,705,"Hansen, Mr. Henrik Juul",26.0,1,0,350025,7.8542,NaN,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
813,814,"Andersson, Miss. Ebba Iris Alfrida",6.0,4,2,347082,31.2750,NaN,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106,107,"Salkjelsvik, Miss. Anna Kristine",21.0,0,0,343120,7.6500,NaN,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
270,271,"Cairns, Mr. Alexander",NaN,0,0,113798,31.0000,NaN,2.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
860,861,"Hansen, Mr. Claus Peter",41.0,2,0,350026,14.1083,NaN,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
435,436,"Carter, Miss. Lucile Polk",14.0,1,2,113760,120.0000,B96 B98,2.0,1.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
102,103,"White, Mr. Richard Frasar",21.0,0,1,35281,77.2875,D26,2.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
deck_encoded = deck_ohe.transform(X_test[['Cabin_Deck']])

X_test = pd.concat([X_test, deck_encoded], axis = 1)

X_test

,PassengerId,Name,Age,SibSp,Parch,Ticket,Fare,Cabin,encoded_pclass,Embarked_C,...,Embarked_nan,Cabin_Deck,Cabin_Deck_B,Cabin_Deck_C,Cabin_Deck_D,Cabin_Deck_E,Cabin_Deck_F,Cabin_Deck_G,Cabin_Deck_T,Cabin_Deck_n
709,710,"Moubarek, Master. Halim Gonios (""William George"")",NaN,1,1,2661,15.2458,NaN,0.0,1.0,...,0.0,n,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
439,440,"Kvillner, Mr. Johan Henrik Johannesson",31.0,0,0,C.A. 18723,10.5000,NaN,1.0,0.0,...,0.0,n,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
840,841,"Alhomaki, Mr. Ilmari Rudolf",20.0,0,0,SOTON/O2 3101287,7.9250,NaN,0.0,0.0,...,0.0,n,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
720,721,"Harper, Miss. Annie Jessie ""Nina""",6.0,0,1,248727,33.0000,NaN,1.0,0.0,...,0.0,n,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
39,40,"Nicola-Yarred, Miss. Jamila",14.0,1,0,2651,11.2417,NaN,0.0,1.0,...,0.0,n,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
433,434,"Kallio, Mr. Nikolai Erland",17.0,0,0,STON/O 2. 3101274,7.1250,NaN,0.0,0.0,...,0.0,n,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
773,774,"Elias, Mr. Dibo",NaN,0,0,2674,7.2250,NaN,0.0,1.0,...,0.0,n,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
25,26,"Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...",38.0,1,5,347077,31.3875,NaN,0.0,0.0,...,0.0,n,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
84,85,"Ilett, Miss. Bertha",17.0,0,0,SO/C 14885,10.5000,NaN,1.0,0.0,...,0.0,n,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
10,11,"Sandstrom, Miss. Marguerite Rut",4.0,1,1,PP 9549,16.7000,G6,0.0,0.0,...,0.0,G,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

In [ ]:
X_train.drop('Cabin_Deck', axis = 1, inplace = True)
X_test.drop('Cabin_Deck', axis = 1, inplace = True)

In [ ]:
X_train

,PassengerId,Name,Age,SibSp,Parch,Ticket,Fare,Cabin,encoded_pclass,Sex_female,...,Cabin_Deck_T,Cabin_Deck_n,Cabin_Deck_B,Cabin_Deck_C,Cabin_Deck_D,Cabin_Deck_E,Cabin_Deck_F,Cabin_Deck_G,Cabin_Deck_T,Cabin_Deck_n
331,332,"Partner, Mr. Austen",45.5,0,0,113043,28.5000,C124,2.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
733,734,"Berriman, Mr. William John",23.0,0,0,28425,13.0000,NaN,1.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
382,383,"Tikkanen, Mr. Juho",32.0,0,0,STON/O 2. 3101293,7.9250,NaN,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
704,705,"Hansen, Mr. Henrik Juul",26.0,1,0,350025,7.8542,NaN,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
813,814,"Andersson, Miss. Ebba Iris Alfrida",6.0,4,2,347082,31.2750,NaN,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106,107,"Salkjelsvik, Miss. Anna Kristine",21.0,0,0,343120,7.6500,NaN,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
270,271,"Cairns, Mr. Alexander",NaN,0,0,113798,31.0000,NaN,2.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
860,861,"Hansen, Mr. Claus Peter",41.0,2,0,350026,14.1083,NaN,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
435,436,"Carter, Miss. Lucile Polk",14.0,1,2,113760,120.0000,B96 B98,2.0,1.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
102,103,"White, Mr. Richard Frasar",21.0,0,1,35281,77.2875,D26,2.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
X_test

,PassengerId,Name,Age,SibSp,Parch,Ticket,Fare,Cabin,encoded_pclass,Embarked_C,...,Embarked_S,Embarked_nan,Cabin_Deck_B,Cabin_Deck_C,Cabin_Deck_D,Cabin_Deck_E,Cabin_Deck_F,Cabin_Deck_G,Cabin_Deck_T,Cabin_Deck_n
709,710,"Moubarek, Master. Halim Gonios (""William George"")",NaN,1,1,2661,15.2458,NaN,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
439,440,"Kvillner, Mr. Johan Henrik Johannesson",31.0,0,0,C.A. 18723,10.5000,NaN,1.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
840,841,"Alhomaki, Mr. Ilmari Rudolf",20.0,0,0,SOTON/O2 3101287,7.9250,NaN,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
720,721,"Harper, Miss. Annie Jessie ""Nina""",6.0,0,1,248727,33.0000,NaN,1.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
39,40,"Nicola-Yarred, Miss. Jamila",14.0,1,0,2651,11.2417,NaN,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
433,434,"Kallio, Mr. Nikolai Erland",17.0,0,0,STON/O 2. 3101274,7.1250,NaN,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
773,774,"Elias, Mr. Dibo",NaN,0,0,2674,7.2250,NaN,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
25,26,"Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...",38.0,1,5,347077,31.3875,NaN,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
84,85,"Ilett, Miss. Bertha",17.0,0,0,SO/C 14885,10.5000,NaN,1.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
10,11,"Sandstrom, Miss. Marguerite Rut",4.0,1,1,PP 9549,16.7000,G6,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

#  Label encoding

In [65]:
from sklearn.preprocessing import LabelEncoder

In [69]:
le = LabelEncoder()

le.fit(y_train)

y_train_array = le.transform(y_train)
y_test_array = le.transform(y_test)

In [70]:
y_train_encoded = pd.Series(y_train_array, index = y_train.index, name = y_train.name)
y_test_encoded = pd.Series(y_test_array, index = y_test.index, name = y_test.name)

In [72]:
y_train_encoded

331    0
733    0
382    0
704    0
813    0
      ..
106    1
270    0
860    0
435    1
102    0
Name: Survived, Length: 712, dtype: int64